name: your_project_name
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

flutter: 
  uses-material-design: true

environment:
  sdk: ">=3.0.0 <4.0.0" # Kept wide to allow older build libraries

dependencies:
  flutter:
    sdk: flutter
   # Network & Auth
  dio: ^5.4.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2 # Required for persistent cookies

  # Real-time
  signalr_netcore: ^1.4.0
  logging: ^1.2.0 # Required for SignalR logging

  # State Management
  provider: ^6.1.1

  # UI & Charting
  fl_chart: ^0.66.0 
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  built_value_generator: 8.9.2 
  build_runner: 2.4.13 